name: OpenAPI Generator

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Mockoon CLI
        uses: mockoon/cli-action@v2
        with:
          # Mockoon CLI version, default to 'latest'
          version: "latest"
          # Mockoon local data file or URL
          data-file: "./src/data/api/openapi.json"
          port: 3003

      - name: Make test call
        run: curl -X GET http://localhost:3003/api/v3/pet/1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Install openapi-generator cli
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Generate API implementation
        run: npm run openapi-generator

      - name: Build
        run: npm run build
